ignore:
  - "Mini Model <minimodel@metamodel.me>"
  - "Scrutinizer Auto-Fixer <auto-fixer@scrutinizer-ci.com>"

exclude:
  languages

mapping:
  Andreas Isaak <info@andreas-isaak.de>: Andreas Isaak <andy.jared@googlemail.com>

copy-left:
   "Stefan Heimes <stefan_heimes@hotmail.com>":
     - contao/config/config.php
     - contao/config/autoload.php
     - contao/dca/tl_metamodel_attribute.php
     - contao/dca/tl_metamodel_dcasetting.php
     - contao/dca/tl_metamodel_rendersetting.php
     - src/MetaModels/Attribute/Timestamp/Timestamp.php
